### ISSUE TITLE
No intuitive way to get group’s access code outside of creation/invitation

### ISSUE THREAD

**Issue by robertniemann** [asmitnayak/TidyUp#13]
When a new group is created, the user is prompted with an access code that new members can use to join the group. However, aside from using the android back button to return to the creation page of that specific instance of that group, I can’t find a way to obtain that access code.

This is a problem of moderate severity, as not having an access code could prove to be troublesome, however there are work-arounds to this such as inviting new members via email.

I would suggest adding the access code in the group settings page, so it is always accessible.

**Comment by monica22schmidt** [comment]
Added this feature to group settings
