### ISSUE TITLE
Rewards are not linked to the tasks

### ISSUE THREAD

**Issue by robertniemann** [asmitnayak/TidyUp#26]
This is more a design question than a bug, but it seems like the rewards and penalties should be linked to the tasks on the list. We don’t understand why these objects are separate

The severity of this issue is moderate, as it is unclear how the rewards are supposed to function.

**Comment by axiong101** [comment]
Rewards or not linked to tasks, rewards are linked to userpoints with rewards point values being the threshold to obtain them
